// <auto-generated />
using System;
using DrawPT.Data.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawPT.MigrationService.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("202505241241_SeedNouns")]
    partial class SeedNouns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.NounEntity", b =>
            {
                b.Property<string>("Noun")
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Noun");

                b.ToTable("Nouns", "ref");
            });
#pragma warning restore 612, 618
        }
    }
} 