// <auto-generated />
using System;
using DrawPT.Data.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawPT.MigrationService.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("202505241143_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "0.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.AdjectiveEntity", b =>
            {
                b.Property<string>("Adjective")
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Adjective");

                b.ToTable("Adjectives", "ref");
            });

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.NounEntity", b =>
            {
                b.Property<string>("Noun")
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Noun");

                b.ToTable("Nouns", "ref");
            });

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.ThemeEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Id");

                b.ToTable("Themes", "ref");
            });
#pragma warning restore 612, 618
        }
    }
}
