// <auto-generated />
using System;

using DrawPT.Data.Repositories;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawPT.MigrationService.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("202506141755_FreepikStyles")]
    partial class FreepikStyles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "0.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrawPT.Data.Repositories.Game.FreepikImageStyleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("FreepikImageStyles", "game");
                });

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.ThemeEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Id");

                b.ToTable("Themes", "ref");
            });
#pragma warning restore 612, 618
        }
    }
}
