// <auto-generated />
using DrawPT.Data.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DrawPT.MigrationService.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("202507091547_AnnouncerPrompts")]
    partial class AnnouncerPrompts20250709
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "0.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrawPT.Data.Repositories.Reference.AnnouncerPromptEntity", b =>
            {
                b.HasKey("Name");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Prompt")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.ToTable("AnnouncerPrompts", "ref");
            });
#pragma warning restore 612, 618
        }
    }
}
